#!/usr/bin/env python3
"""Remove autogenerated object entries while preserving real source TUs."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def clean(path: Path) -> None:
    data = json.loads(path.read_text(encoding="utf-8"))
    for library in data.values():
        objects = library.get("objects", {})
        library["objects"] = {
            source: status
            for source, status in objects.items()
            if (Path("src") / source).is_file()
        }
    path.write_text(json.dumps(data, indent=4) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("paths", type=Path, nargs="+")
    args = parser.parse_args()
    for path in args.paths:
        clean(path)


if __name__ == "__main__":
    main()
