#!/usr/bin/env python3
"""Remove autogenerated per-function groups from editable splits files."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


GENERATED_GROUP = re.compile(r"^(?:\d{4}_|__)")


def clean(path: Path) -> None:
    lines = path.read_text(encoding="utf-8").splitlines()
    output: list[str] = []
    keep = True
    for line in lines:
        stripped = line.strip()
        if not stripped or stripped == "Sections:":
            output.append(line)
            continue
        if not line.startswith(" ") and stripped.endswith(":"):
            keep = not GENERATED_GROUP.match(stripped[:-1])
        if keep:
            output.append(line)
    path.write_text("\n".join(output).rstrip() + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("paths", type=Path, nargs="+")
    args = parser.parse_args()
    for path in args.paths:
        clean(path)


if __name__ == "__main__":
    main()
